### ISSUE TITLE
Passing Functions

### ISSUE THREAD

**Issue by kaendfinger** [mezoni/binary_interop#12]
I don't really know much about C, as displayed in my last issue, but I know you can pass functions/methods into a method call. I need this because OpenGL requires that.

Is this even possible to implement in binary_interop? I am pretty sure I need this. You can see this here: https://www.opengl.org/archives/resources/code/samples/glut_examples/examples/cube.c

**Comment by mezoni** [comment]
This is a long story and a lot of work.
Recently, I was reminded of this.
I'll do it after a detailed plan.
This feature callled `callback` function.
In terms of `libffi`, it is a `closure`.

**Comment by kaendfinger** [comment]
@mezoni Awesome :) I know it's a lot of work, that's why I'm asking.

**Comment by mezoni** [comment]
Not a much work to implement but a much work to rethink.
This will be the final stage.
That is, all features implemented.

**Comment by kaendfinger** [comment]
Cool :)

**Comment by mezoni** [comment]
It works. Dart code called from C code.

```c
EXTERN_C void test_callback(char *cp, int (fn)(char *cp)) {
  int ret = 0;
  ret = fn(cp);  
  printf("C code: Dart return %i\n", ret);  
}
```

```dart
    test("Callback", () {
      var functionType = t["callback_t"];
      int cb(List<BinaryData> arguments, Object userData) {
        var c = arguments[0].value;
        var str = helper.readString(c);        
        print("Dart code: I get from C '$str'");
        return 41;
      };

      var callback = new BinaryCallback(functionType, cb);
      var string = helper.allocString("It works!");      
      var fn = functionType.extern(callback.address);
      lib.invokeEx("test_callback", [string, fn]);
    });
```

```
Dart code: I get from C 'It works!'
C code: Dart return 41
```

Not ready for public use but already works.

**Comment by mezoni** [comment]
@kaendfinger 

The following modifications was made (packages):
- binary_interop (was moved part of code to the new package)
- unsafe_extension (was moved part of code to the new package)
- libffi_extension (new)
- libffi_support (new)

Will be need a compilation of the native extensions for different platforms (ARM, Android, Mac OS).

**Comment by kaendfinger** [comment]
Thanks! :) I'll recompile the stuff.

**Comment by mezoni** [comment]
>> Thanks! :) I'll recompile the stuff.

Very good!
Remains last work. The finalyzer of the closures (auto freeing them through the call `ffi_closure_free()` in native extension).
I don't like any manual call such as the `resource.free()`.

**Comment by kaendfinger** [comment]
@mezoni :) Awesome. I'm excited to get OpenGL :D

**Comment by kaendfinger** [comment]
@mezoni Also, I have repurposed syscall a bit. Instead of just simple bindings for LibC, it is now a high level API for working with multiple libraries. It basically has a namespace system I wrote. I'm working on bindings to multiple libraries to add to it :)

**Comment by mezoni** [comment]
@kaendfinger 

>> @mezoni :) Awesome. I'm excited to get OpenGL :D

Programming callback will be not easy. Not hard but not so comfortable.
This is not a my mistake. This is a limitation of such bridges.
Because callback will take the arguments through the list of arguments.

Eg.

```
    // Hint: int (*pcallback_t)(char *cp)
     int cb(List<BinaryData> arguments) {
       // char *cp
        var c = arguments[0].value;
        var str = helper.readString(c);
        print("Dart code: I get from C '$str'");
        return 41;
      };

      var functionType = (t["pcallback_t"] as PointerType).type;
      var callback = new BinaryCallback(functionType, cb);
      var string = helper.allocString("It works!");
      lib.invokeEx("test_callback", [string, callback.functionCode]);      
    });
```

Also I decided to preserve binary types in arguments instead of just to give the access to the values.
This makes it (callback handler) more powerful with full information about the arguments and their binary types.

**Comment by kaendfinger** [comment]
@mezoni Awesome :)

**Comment by mezoni** [comment]
>> Also, I have repurposed syscall a bit.

Good things!
Look at the `golang syscall`
https://golang.org/src/syscall/zsyscall_linux_amd64.go

It also uses binary interop.

```go
func Creat(path string, mode uint32) (fd int, err error) {
  	var _p0 *byte
  	_p0, err = BytePtrFromString(path)
  	if err != nil {
  		return
  	}
  	r0, _, e1 := Syscall(SYS_CREAT, uintptr(unsafe.Pointer(_p0)), uintptr(mode), 0)
  	use(unsafe.Pointer(_p0))
  	fd = int(r0)
  	if e1 != 0 {
  		err = e1
  	}
  	return
  }
```

**Comment by kaendfinger** [comment]
That's awesome. I'm excited to get this up and running.

**Comment by kaendfinger** [comment]
@mezoni 
Given `snappy_status snappy_compress(const char* input,
                              size_t input_length,
                              char* compressed,
                              size_t* compressed_length);`

What should I do to convert a List<int> into the char*?

**Comment by kaendfinger** [comment]
@mezoni I need to know something real quick.

Found in an Ruby Binding for Snappy (The library I am creating bindings for) this:

```ruby
    FFI::MemoryPointer.new(max) { |output_buffer|
```

What would be the equivalent of that.

**Comment by mezoni** [comment]
>> snappy

Use Dart `List<int>` and binary `char[]`.

```dart
import "package:binary_interop/binary_interop.dart";

void main() {
  var t = new BinaryTypes();
  var h = new BinaryTypeHelper(t);
  var data = _getData();
  var length = data.length;
  // Now data in 'char[]'
  var buffer = t["char[$length]"].alloc(data); 
  for (var i = 0; i < length; i++) {
    print(buffer[i].value);
  }
}

List<int> _getData() {
  return <int>[0, 1, 2, 3, 4, 5];
}

```

**Comment by kaendfinger** [comment]
I have an error:

```dart
  static String compress(String input) {
    var inputString = toNativeString(input);
    var maxOutputSize = alloc("size_t", getMaxCompressedLength(inputString.type.size));
    var rs = allocArray("char", maxOutputSize.value);
    var status = getStatus(invoke("snappy::snappy_compress", [inputString, inputString.type.size, rs, maxOutputSize]));
    if (status != SnappyStatus.OK) {
      throw new SnappyException(status);
    }
    List<int> bytes = rs.value;
    print(bytes);
    print(maxOutputSize.value);
    return readNativeString(rs);
  }
```

```
[101, 36, 49, 50, 51, 52, 53, 54, 55, 56, 57, 48, -2, 10, 0, 102, 10, 0, 0, 0, 1, 0, 0, 0, -102, -20, -89, 13, 0, 0, 0, 0, -47, -51, -116, 9, 1, 0, 0, 0, -15, 125, 58, 59, 0, 0, 0, 0, -31, -43, -116, 9, 1, 0, 0, 0, -71, 69, 40, 49, 0, 0, 0, 0, -15, -69, -116, 9, 1, 0, 0, 0, -4, -87, 87, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, -69, 10, 1, 0, 0, 0, 105, -50, -69, 10, 1, 0, 0, 0, 41, -49, -69, 10, 1, 0, 0, 0, 105, -49, -69, 10, 1, 0, 0, 0, 41, -48, -69, 10, 1]
20
Unhandled exception:
Invalid argument(s): [101, 36, 49, 50, 51, 52, 53, 54, 55, 56, 57, 48, -2, 10]
#0      _StringBase.createFromCharCodes (dart:core-patch/string_patch.dart:133)
#1      String.String.fromCharCodes (dart:core-patch/string_patch.dart:16)
#2      BinaryTypeHelper.readString (package:binary_types/src/type_helper.dart:168:16)
#3      readNativeString (package:syscall/src/core.dart:444:36)
#4      Snappy.compress (package:syscall/snappy.dart:65:12)
#5      main (file:///Users/alex/DirectCode/SystemCalls/example/snappy.dart:5:23)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by mezoni** [comment]
Snappy can compress only strings?
That is, only null terminated byte sequences?

**Comment by kaendfinger** [comment]
@mezoni Yes, I believe so.

See https://github.com/willglynn/snappy-ruby/blob/master/snappy_ffi/lib/snappy_ffi.rb#L35

**Comment by mezoni** [comment]
Why need see examples in Ruby?
Why not look at examples in C?

Binary types are more similar to C language.
If you know C language then you can easy use binary types.

P.S.
Don't use strings. Use bytes.

**Comment by kaendfinger** [comment]
Ok.

**Comment by mezoni** [comment]
Problem in your Dart code.

>> Invalid argument(s): [101, 36, 49, 50, 51, 52, 53, 54, 55, 56, 57, 48, -2, 10]

-2 cannot be used in Dart String.

**Comment by kaendfinger** [comment]
@mezoni Yes, trying to figure out why it gives that.

**Comment by kaendfinger** [comment]
@mezoni I think I might have fixed it. I'll double check.

**Comment by mezoni** [comment]
>> FFI::MemoryPointer.new(max) { |output_buffer|
>> What would be the equivalent of that.

Binary types are more powerfull and more similar to C language.

Eg.

```dart
var p1 = type["YOUR_TYPE"].array(length).alloc(initialValue);
var p2 = type["YOUR_TYPE[$length]"].alloc(initialValue);
``

**Comment by mezoni** [comment]
Does not forget that C string does not compatible with Dart Strings.
Dart String are wide string (16-bit).
C language type 'char'  often has size 8-bit.

**Comment by kaendfinger** [comment]
@mezoni Take a look at https://github.com/DirectMyFile/syscall/blob/master/lib/snappy.dart

**Comment by mezoni** [comment]
Dart String `code units` should be additionaly divided on the 8-bit values before you can passing them to C language function.
Otherwise, when you convert data values will be distorted.
Or you should use `wchar_t` version of C language function.

**Comment by mezoni** [comment]
I eat after work.

**Comment by mezoni** [comment]
I modified your code and it works as expected.
But I found some problems.
In C language `char` is signed [-128..127].
UTF-8 is 8-bit.
UTF-8 value `208` means `-48`.
In C language this has no sence because `208` and `-48` means the same bits in memory.
But in Dart this is a diffirent numbers.
I never take this into account.
Need thinking.

**Comment by mezoni** [comment]
`BinaryTypeHelper.readString()` was modified.
Currently `binary_types` involved in the `binary_interop` modification.
I will update it later when `BinaryCallback` will be ready.

**Comment by kaendfinger** [comment]
Awesome :)

**Comment by mezoni** [comment]
`Passing Functions ` ready.
Today I will perform the tests of the `libffi6` native extension on the Windows and publish all packages on GitHub.
I think that everything will work well.

**Comment by kaendfinger** [comment]
@mezoni Let me know when it is ready :)

**Comment by mezoni** [comment]
>> @mezoni Let me know when it is ready :)

Yes, of course.

I decided provide two kind of callback functions (binary and native).

```dart
BinaryCallback(FunctionType functionType, {
  BinaryInterface abi,
  CallingConvention callingConvention,
  void binary(List<BinaryData> arguments, BinaryData returns),
  dynamic native(List arguments)}) {
```

Example:

```dart
    test("Callback (binary)", () {
      void cb(List<BinaryData> arguments, BinaryData returns) {
        var c = arguments[0].value;
        var str = helper.readString(c);
        print("Dart code: I get from C '$str'");
        returns.value = c;
      }

      var functionType = (t["pcallback_t"] as PointerType).type;
      var callback = new BinaryCallback(functionType, binary: cb);
      var string = helper.allocString("It works!");
      lib.invokeEx("test_callback", [string, callback.functionCode]);
    });

    test("Callback (native)", () {
      dynamic cb(List arguments) {
        var c = arguments[0];
        var str = helper.readString(c);
        print("Dart code: I get from C '$str'");
        return c;
      }

      var functionType = (t["pcallback_t"] as PointerType).type;
      var callback = new BinaryCallback(functionType, native: cb);
      var string = helper.allocString("It works!");
      lib.invokeEx("test_callback", [string, callback.functionCode]);
    });
```

Native method are simple but not always possible correctly represent binary data as Dart object.

Eg. C language unions. Dart does not support them.
Of course, they represent as the `Map` but in some case better use binary data directly.
That is, you can choose the kind of the callback for you requirements.

**Comment by kaendfinger** [comment]
@mezoni Will this solve the string issue as well?

**Comment by mezoni** [comment]
>> @mezoni Will this solve the string issue as well?

No. Not related to this issue.

As I wrote:
`BinaryTypeHelper.readString()` was modified.

That is, it should correctly accept and convert negative values to positive values.
This will solve the string issue.

**Comment by kaendfinger** [comment]
Ok :) Great

**Comment by mezoni** [comment]
I think you may compile these packages:
https://github.com/mezoni/libffi6_extension
https://github.com/mezoni/unsafe_extension

I already compiled them for Windows and Linux.

**Comment by kaendfinger** [comment]
@mezoni Ok, I'm at school, I will be at home in ~3 hours, then I will compile.

**Comment by mezoni** [comment]
OK.

**Comment by mezoni** [comment]
I will sleep at that time.

**Comment by kaendfinger** [comment]
@mezoni Are you waiting for me to compile before you push the other changes?

**Comment by mezoni** [comment]
No.

**Comment by kaendfinger** [comment]
Ok, just making sure.

**Comment by mezoni** [comment]
Troubles with pub transformers.

For example, consider three transformers, specified as follows:
transformers:
- [t1, t2]
- t3
The t1 and t2 transformers run first, in parallel. The t3 transformer runs in a separate phase, after t1 and t2 are finished, and can see the outputs of t1 and t2.

```
The t3 transformer runs in a separate phase, after t1 and t2 are finished, and can see
the outputs of t1 and t2.
```

But what I have.


Loading source assets...
Loading libffi6_extension and unsafe_extension transformers...
libffi6_extension aplly
libffi6_extension cwd: /home/andrew/dart/for_web/libffi6_support
unsafe_extension started
unsafe_extension cwd: /home/andrew/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.1/lib/src
Setup libffi6_extension.so.
Copying compiled binary 'compiled/X86/linux/libffi6_extension.so'
The setup successful.
libffi6_extension finished
Transform NativeExtensionBuilder on unsafe_extension|lib/src/unsafe_extension.inf threw error: Cannot resolve symbolic links, path = '/home/andrew/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.1/lib/src/packages/unsafe_extension' (OS Error: No such file or directory, errno = 2)


Precompiling dependencies...
Loading source assets...
Loading libffi6_extension and unsafe_extension transformers...
**libffi6_extension started**
libffi6_extension cwd: /home/andrew/dart/for_web/libffi6_support
**unsafe_extension started**
unsafe_extension cwd: /home/andrew/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.1/lib/src
Setup libffi6_extension.so.
Copying compiled binary 'compiled/X86/linux/libffi6_extension.so'
The setup successful.
**libffi6_extension finished**

That is.

```
libffi6_extension started
unsafe_extension started
libffi6_extension finished
```

Unexpected behavior bacause I need save/change/restore current working directory.

**Comment by mezoni** [comment]
fucking pub...

**Comment by mezoni** [comment]
https://code.google.com/p/dart/issues/detail?id=23318

Now extension cannot be installed through the transformers due the this bug in `pub manager`.

**Comment by kaendfinger** [comment]
Ok. I'll see what I can do to help :)

**Comment by mezoni** [comment]
>> Ok. I'll see what I can do to help :)

mystrom replied that my issue are invalid and does not want explain why one transformer will start before the previous was not finished.

https://code.google.com/p/dart/issues/detail?id=23318

**Comment by kaendfinger** [comment]
@mezoni How can I simulate this? Also:

```
➜ SystemCalls git:(master) dart example/snappy.dart
'package:binary_interop/internal/foreign_function/src/foreign_function.dart': error: line 331 pos 14: expression is not a valid compile-time constant
        case BinaryKinds.STRUCT:
             ^
```

I guess this is because binary_interop isn't updated yet.

**Comment by mezoni** [comment]
Yes.
Need solve problem with pub transformers.

**Comment by mezoni** [comment]
Why they run in parallel?

**Comment by kaendfinger** [comment]
@mezoni I'm debugging it, but how do I simulate this problem?

**Comment by mezoni** [comment]
Without this native extensions does not works.
Need manual procedures of intallation.

**Comment by kaendfinger** [comment]
@mezoni You could actually just hack it:

Instead of running the installer in the same process, spawn a new process for the installer.

**Comment by mezoni** [comment]
Create package that use both extensions
- libff6
- unsafe

Delete `pubspec.lock`
run pub get
They will run in parallel

**Comment by mezoni** [comment]
But why?
Documenation says:
One finished, next started.
I am about transformers.

**Comment by kaendfinger** [comment]
@mezoni I don't think this happens on Dart v1.11 https://gist.github.com/kaendfinger/d58ddda24b2619a31973

**Comment by kaendfinger** [comment]
Or maybe I am just reading that log wrong?

**Comment by kaendfinger** [comment]
Oh wait, it's not compiled for mac yet.

**Comment by mezoni** [comment]
You wrong.

I found only
Copying compiled binary 'compiled/X86_64/macos/libunsafe_extension.dylib'

Where you find?

Copying compiled binary 'compiled/X86_64/macos/libffi6_extension.dylib'

This is because `build_tools` cannot run in parallel.

**Comment by mezoni** [comment]
But transformers also shoud not run in parallel.

**Comment by kaendfinger** [comment]
Ok, i'll check into this.

**Comment by mezoni** [comment]
This is wrong work of pub manager.
See here.

==============> Start libffi6_extension
Some work
==============> Start unsafe_extension
Some work
Other work
==============> Finished libffi6_extension
==============> Finished unsafe_extension

**Comment by mezoni** [comment]
Should be

==============> Start libffi6_extension
Some work
Other work
==============> Finished libffi6_extension
==============> Start unsafe_extension
Some work
Other work
==============> Finished unsafe_extension

**Comment by mezoni** [comment]
```dart
library libffi_extension.transformer;

import "dart:io";

import "package:barback/barback.dart";
import "package:file_utils/file_utils.dart";
import "package:libffi6_extension/src/installer.dart";
import "package:path/path.dart" as lib_path;

class NativeExtensionBuilder extends Transformer {
  static const String EXT = ".inf";

  static const String PACKAGE = "libffi6_extension";

  final BarbackSettings _settings;

  String _workingDirectory;

  NativeExtensionBuilder.asPlugin(this._settings) {
    _workingDirectory = Directory.current.path;
  }

  String get allowedExtensions => EXT;

  dynamic apply(Transform transform) async {
    var id = transform.primaryInput.id;
    if (id.package != PACKAGE) {
      return null;
    }

    var filepath = id.path;
    if (lib_path.basename(filepath) != "$PACKAGE$EXT") {
      return null;
    }

    try {
      var path = _resolvePackagePath(filepath);
      FileUtils.chdir(path);
      var installer = new Installer();
      await installer.install([]);
    } finally {
      FileUtils.chdir(_workingDirectory);
    }

    return null;
  }

  // This is incorrect but there is no other way
  String _resolvePackagePath(String filepath) {
    var path = lib_path.join(_workingDirectory, "packages", PACKAGE);
    path = new Link(path).resolveSymbolicLinksSync();
    path = lib_path.dirname(path);
    return path;
  }
}
```

**Comment by mezoni** [comment]
Add some hooks in pub-cache and see results.
They will start simultaneously.
At least, second not waits first and executes.

Eg.

```dart
      print("$PACKAGE start");

 try {
      var path = _resolvePackagePath(filepath);
      FileUtils.chdir(path);
      var installer = new Installer();
      await installer.install([]);
    } finally {
      FileUtils.chdir(_workingDirectory);
    }

    print("$PACKAGE finished");
```

**Comment by mezoni** [comment]
You know that pub manager cannot resolve dependenies of himself?
At least on slow machines it fails due the timeout.
You can try.
It is simply amazing.

- Download pub source
- Create manualy `pubspec.yaml`
- Step by step add manually dependenies to `pubspec.yaml`
- See how it works and enjoy

On my AMD A4-3400 pub always fails due the hard work.

**Comment by mezoni** [comment]
I go sleep...

**Comment by kaendfinger** [comment]
I'm debugging it for you :)

**Comment by mezoni** [comment]
Please, explain me how to debug transformers in pub manager?
How to set breakpoints in `Transformer.apply()`?

**Comment by mezoni** [comment]
I can use only hooks and they say:
Method `apply()` of the next transformer was entered before the previous transformer leaves the body of their own `apply()`.

**Comment by kaendfinger** [comment]
@mezoni I'm actually modifying pub itself to get info about what it's doing.

It seems it's creating a single stage.

Transformer Stages: [{libffi6_extension, unsafe_extension}]

**Comment by mezoni** [comment]
This is very bad.
They uses the same extension

```
static const String EXT = ".inf";
String get allowedExtensions => EXT;
```

They cannot run in parallel,

**Comment by mezoni** [comment]
Only programmer can join them in single stage in `pubspec.yaml`.

Eg.
- [t1, t2]
t3

**Comment by mezoni** [comment]
Eg.
```
- [t1, t2]
- t3
```

**Comment by mezoni** [comment]
I will publish package `lock` for such purpose.

> The "lock" is a soft locking which prevent the simultaneous execution of the "locked" code. Does not lock a whole program or the previously runned code.

```dart
import "dart:async";

import "package:lock/lock.dart";

Future main() async {
  var a1 = action("2 sec", new Duration(seconds: 2));
  var a2 = action("1 sec", new Duration(seconds: 1));
  Future.wait([a1, a2]);
  var l1 = locked("2 sec", new Duration(seconds: 2));
  var l2 = locked("1 sec", new Duration(seconds: 1));
  Future.wait([l1, l2]);
}

Future action(String text, Duration duration, [String info = ""]) async {
  print("${info}Started: $text");
  await new Future.delayed(duration);
  print("${info}Finished: $text");
}

int _lockId = 0;

Future locked(String text, Duration duration) async {
  await lock(() async {
    _lockId++;
    await action("$text", duration, "Lock #$_lockId: ");
  });

  print("Unlocked #$_lockId");
}
```

Result:

```
Started: 2 sec
Started: 1 sec
Lock #1: Started: 2 sec
Finished: 1 sec
Finished: 2 sec
Lock #1: Finished: 2 sec
Unlocked #1
Lock #2: Started: 1 sec
Lock #2: Finished: 1 sec
Unlocked #2
```

**Comment by mezoni** [comment]
Maybe in Dart already exists such feature and don't need create a such package?
But I already implemented it.

**Comment by mezoni** [comment]
@kaendfinger 
I published all packages. You can test your wishes.
I tested and they works.

I will solve  the problem with installation of  the native extensions from the transformers.

**Comment by mezoni** [comment]
Need compile unsafe extension for Mac OS.

**Comment by kaendfinger** [comment]
Ok, I'll do that now.

**Comment by mezoni** [comment]
Can I delete all our talks here?

**Comment by kaendfinger** [comment]
Yes
