### ISSUE TITLE
Casting Support

### ISSUE THREAD

**Issue by kaendfinger** [mezoni/binary_interop#17]
It would be great to support casting.

**Comment by mezoni** [comment]
Good to see you again!
It has always existed.
In `binary_types`.

https://github.com/mezoni/binary_types/blob/master/test/test_binary_types.dart#L507

https://github.com/mezoni/binary_types/blob/master/test/test_binary_types.dart#L535

https://github.com/mezoni/binary_types/blob/master/test/test_binary_types.dart#L539

**Comment by kaendfinger** [comment]
Ahh, thanks. Didn't know that.

**Comment by mezoni** [comment]
Now you know about it.

**Comment by mezoni** [comment]
I no longer have been programming in Google Dart language.
It does not bring any income.
And besides, there is no pleasure to do something for Google.
Google Dart developers never listened to the wishes of users.
Let them work for the benefit of their own pockets.
P.S.
For me Google Dart is a hopeless software product.
