### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by kaendfinger** [mezoni/binary_interop#5]
Now that we have libffi and unsafe_extension for Android, can you tell me what all I need to do to get this working binary_introp?

**Comment by mezoni** [comment]
>> Now that we have libffi and unsafe_extension for Android, can you tell me what all I need to do to get this working binary_introp?

Great work of adding `libffi` and` unsafe extension` for Android.
I'll make some additions into the `binary interop` and you can perform tests on Android.

This may require to look on the source code of `libffi`.

Now 8.48 a.m. and today are working day (for me).

**Comment by kaendfinger** [comment]
Ok :)

**Comment by mezoni** [comment]
I need info from the generatated directory inside 'libfii'.
I don't know how it called on Android but here is examples:
- i686-pc-mingw32
- i686-pc-linux-gnu

I think it maybe be called `arm-android-linux-gnu`

I need all files (full directory) to analyze settings of this configuration (compilation).

**Comment by mezoni** [comment]
Or you can answer me:
Which ARM you use when compile `libffi`?
- ARM ABI
- ARM EABI (VFP)

**Comment by mezoni** [comment]
-mfloat-abi=name
Specifies which floating-point ABI to use. Permissible values are: `soft', `softfp' and `hard'.
Specifying `soft' causes GCC to generate output containing library calls for floating-point operations. `softfp' allows the generation of code using hardware floating-point instructions, but still uses the soft-float calling conventions. `hard' allows generation of floating-point instructions and uses FPU-specific calling conventions.

Using -mfloat-abi=hard with VFP coprocessors is not supported. Use -mfloat-abi=softfp with the appropriate -mfpu option to allow the compiler to generate code that makes use of the hardware floating-point capabilities for these CPUs.

The default depends on the specific target configuration. Note that the hard-float and soft-float ABIs are not link-compatible; you must compile your entire program with the same ABI, and link with a compatible set of libraries. 

-mhard-float
Equivalent to -mfloat-abi=hard. 
-msoft-float
Equivalent to -mfloat-abi=soft

**Comment by kaendfinger** [comment]
@mezoni For Android, use arm-linux-androideabi

**Comment by kaendfinger** [comment]
I'll copy the files into a zip for ya.

**Comment by mezoni** [comment]
Dart VM for ARM also compiled with `-mhard-float?`

```
The default depends on the specific target configuration. Note that the hard-float and soft-float ABIs are not link-compatible; you must compile your entire program with the same ABI, and link with a compatible set of libraries.
```

**Comment by kaendfinger** [comment]
http://directcode.org/libffi.zip has the entire libffi directory.

No hard float.

**Comment by mezoni** [comment]
You can try it.
Maybe I forgot something.
If that does not work then we will look for the problem.

**Comment by mezoni** [comment]
>> http://directcode.org/libffi.zip has the entire libffi directory.

Thank you.
I found required information.

**Comment by kaendfinger** [comment]
I'll start tests :)
