### ISSUE TITLE
Full ARM Support

### ISSUE THREAD

**Issue by kaendfinger** [mezoni/binary_interop#7]
@mezoni Since I added libffi binaries for ARM, can you add support for that as well? The zip I sent you should contain all the info.

I'm using this on my Raspberry Pi to build things that interact with USB.

**Comment by mezoni** [comment]
>> Since I added libffi binaries for ARM, can you add support for that as well? 

Sorry, but I don't understand you.What means "add support for that as well".
I forgotten to do something?

>> The zip I sent you should contain all the info.

I use it only for look on generated configuaration for modifing Dart code.
What I should add?
Please, explain problem in more detail (error messages will come in handy).

**Comment by kaendfinger** [comment]
@mezoni You added Android support, does that work for normal non-Android devices as well? I want to make sure that the ARM support works for not only Android, but also any other ARM device.

**Comment by mezoni** [comment]
>> You added Android support, does that work for normal non-Android devices as well? I want to make sure that the ARM support works for not only Android, but also any other ARM device.

This impossible because problem is more widely.
Each task inputs.
Your inputs was:
- ARM (CPU)
- Android (OS)

What is next task?
- ARM (CPU)
- All other os (DEBIAN, Free BSD, IOS)

Each task consist (for libffi) from two inputs
- CPU
- OS

Sub tasks
- CPU Bitness
- OS bitness

P.S.
It works on Android?

P.S.
I don't have ARM in any form for use it

**Comment by kaendfinger** [comment]
@mezoni I'm testing it out now, just got my new ARM device :)

**Comment by mezoni** [comment]
>> You added Android support, does that work for normal non-Android devices as well? I want to make sure that the ARM support works for not only Android, but also any other ARM device.

Look at "libffi" source.
Priority 0 (High) - CPU (Not operating system)
Priority 1 - Operating (sub)system

>> ARM device.

What means a device?
From the hardware "libffi" recognizes only processors and emulators (eg. for floating points) but not devices.
From the software it recognizes only operating systems.
And of course, it detects compiler features and settings.

Please, explain your wishes only in these terms (CPU, OS).

**Comment by kaendfinger** [comment]
@mezoni Actually, it probably works then :) Nevermind

**Comment by mezoni** [comment]
>> You added Android support, does that work for normal non-Android devices as well?

Need tests.
Look at the "libffi" versions history.
It was not written at one time.
Some wish -> tester -> implementation
Also required software and hardware.

**Comment by mezoni** [comment]
> Actually, it probably works then :) Nevermind

Please explain in tradiotional English.

**Comment by kaendfinger** [comment]
@mezoni libffi should work on ARM. I am testing it now. From what you said, it will indeed work, I can now close this issue.

**Comment by mezoni** [comment]
>> From what you said, it will indeed work, I can now close this issue.

OK.

>> The zip I sent you should contain all the info.

It contains binaries that will work only on the ARM Android (w/o full ARM support).

**Comment by kaendfinger** [comment]
@mezoni Making a PR on unsafe_extension to fix compilation, and add a build of the extension.
